#[doc = "Register `AUTO_CMD_STAT_R` reader"]
pub type R = crate::R<AutoCmdStatRSpec>;
#[doc = "Field `AUTO_CMD12_NOT_EXEC` reader - Auto CMD12 Not Executed If multiple memory block data transfer is not started due to a command error, this bit is not set because it is not necessary to issue an Auto CMD12. Setting this bit to 1 means that the Host Controller cannot issue Auto CMD12 to stop multiple memory block data transfer, due to some error. If this bit is set to 1, error status bits (D04-D01) is meaningless. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Executed - 0x0 (FALSE): Executed"]
pub type AutoCmd12NotExecR = crate::BitReader;
#[doc = "Field `AUTO_CMD_TOUT_ERR` reader - Auto CMD Timeout Error This bit is set if no response is returned with 64 SDCLK cycles from the end bit of the command. If this bit is set to 1, error status bits (D04-D01) are meaningless. Values: - 0x1 (TRUE): Time out - 0x0 (FALSE): No Error"]
pub type AutoCmdToutErrR = crate::BitReader;
#[doc = "Field `AUTO_CMD_CRC_ERR` reader - Auto CMD CRC Error This bit is set when detecting a CRC error in the command response. Values: - 0x1 (TRUE): CRC Error Generated - 0x0 (FALSE): No Error"]
pub type AutoCmdCrcErrR = crate::BitReader;
#[doc = "Field `AUTO_CMD_EBIT_ERR` reader - Auto CMD End Bit Error This bit is set when detecting that the end bit of command response is 0. Values: - 0x1 (TRUE): End Bit Error Generated - 0x0 (FALSE): No Error"]
pub type AutoCmdEbitErrR = crate::BitReader;
#[doc = "Field `AUTO_CMD_IDX_ERR` reader - Auto CMD Index Error This bit is set if the command index error occurs in response to a command. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
pub type AutoCmdIdxErrR = crate::BitReader;
#[doc = "Field `AUTO_CMD_RESP_ERR` reader - Auto CMD Response Error This bit is set when Response Error Check Enable in the Transfer Mode register is set to 1 and an error is detected in R1 response of either Auto CMD12 or CMD13. This status is ignored if any bit between D00 to D04 is set to 1. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
pub type AutoCmdRespErrR = crate::BitReader;
#[doc = "Field `CMD_NOT_ISSUED_AUTO_CMD12` reader - Command Not Issued By Auto CMD12 Error If this bit is set to 1, CMD_wo_DAT is not executed due to an Auto CMD12 Error (D04-D01) in this register. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Issued - 0x0 (FALSE): No Error"]
pub type CmdNotIssuedAutoCmd12R = crate::BitReader;
impl R {
    #[doc = "Bit 0 - Auto CMD12 Not Executed If multiple memory block data transfer is not started due to a command error, this bit is not set because it is not necessary to issue an Auto CMD12. Setting this bit to 1 means that the Host Controller cannot issue Auto CMD12 to stop multiple memory block data transfer, due to some error. If this bit is set to 1, error status bits (D04-D01) is meaningless. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Executed - 0x0 (FALSE): Executed"]
    #[inline(always)]
    pub fn auto_cmd12_not_exec(&self) -> AutoCmd12NotExecR {
        AutoCmd12NotExecR::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Auto CMD Timeout Error This bit is set if no response is returned with 64 SDCLK cycles from the end bit of the command. If this bit is set to 1, error status bits (D04-D01) are meaningless. Values: - 0x1 (TRUE): Time out - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_tout_err(&self) -> AutoCmdToutErrR {
        AutoCmdToutErrR::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Auto CMD CRC Error This bit is set when detecting a CRC error in the command response. Values: - 0x1 (TRUE): CRC Error Generated - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_crc_err(&self) -> AutoCmdCrcErrR {
        AutoCmdCrcErrR::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Auto CMD End Bit Error This bit is set when detecting that the end bit of command response is 0. Values: - 0x1 (TRUE): End Bit Error Generated - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_ebit_err(&self) -> AutoCmdEbitErrR {
        AutoCmdEbitErrR::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Auto CMD Index Error This bit is set if the command index error occurs in response to a command. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_idx_err(&self) -> AutoCmdIdxErrR {
        AutoCmdIdxErrR::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Auto CMD Response Error This bit is set when Response Error Check Enable in the Transfer Mode register is set to 1 and an error is detected in R1 response of either Auto CMD12 or CMD13. This status is ignored if any bit between D00 to D04 is set to 1. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_resp_err(&self) -> AutoCmdRespErrR {
        AutoCmdRespErrR::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 7 - Command Not Issued By Auto CMD12 Error If this bit is set to 1, CMD_wo_DAT is not executed due to an Auto CMD12 Error (D04-D01) in this register. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Issued - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn cmd_not_issued_auto_cmd12(&self) -> CmdNotIssuedAutoCmd12R {
        CmdNotIssuedAutoCmd12R::new(((self.bits >> 7) & 1) != 0)
    }
}
#[doc = "Auto CMD Status Register\n\nYou can [`read`](crate::Reg::read) this register and get [`auto_cmd_stat_r::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct AutoCmdStatRSpec;
impl crate::RegisterSpec for AutoCmdStatRSpec {
    type Ux = u16;
}
#[doc = "`read()` method returns [`auto_cmd_stat_r::R`](R) reader structure"]
impl crate::Readable for AutoCmdStatRSpec {}
#[doc = "`reset()` method sets AUTO_CMD_STAT_R to value 0"]
impl crate::Resettable for AutoCmdStatRSpec {
    const RESET_VALUE: u16 = 0;
}
