#[doc = "Register `CQCRDCT` reader"]
pub type R = crate::R<CqcrdctSpec>;
#[doc = "Field `DCMD_RESP` reader - This register contains the response of the command generated by the last direct command (DCMD) task that was sent. Contents of this register are valid only after bit 31 of CQTDBR register is cleared by the controller."]
pub type DcmdRespR = crate::FieldReader<u32>;
impl R {
    #[doc = "Bits 0:31 - This register contains the response of the command generated by the last direct command (DCMD) task that was sent. Contents of this register are valid only after bit 31 of CQTDBR register is cleared by the controller."]
    #[inline(always)]
    pub fn dcmd_resp(&self) -> DcmdRespR {
        DcmdRespR::new(self.bits)
    }
}
#[doc = "Command response for direct command register\n\nYou can [`read`](crate::Reg::read) this register and get [`cqcrdct::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct CqcrdctSpec;
impl crate::RegisterSpec for CqcrdctSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`cqcrdct::R`](R) reader structure"]
impl crate::Readable for CqcrdctSpec {}
#[doc = "`reset()` method sets CQCRDCT to value 0"]
impl crate::Resettable for CqcrdctSpec {
    const RESET_VALUE: u32 = 0;
}
